### PR TITLE
Show campaign name in create proposal form

### PR DESCRIPTION
**Pull request by PAkhidue**
Shows name instead of address when creating a proposal for a campaign.

### CODE REVIEW

**Comment by 2075** [comment]
lgtm

**Comment by soundyogi** [comment]
I am too stupid to find this.
(vercel deploy and locally)

I created an org and 2 campaigns. (with dao governance)

can I have a screenshot where it is supposed to be?

**Comment by Persqual** [comment]
> I am too stupid to find this. (vercel deploy and locally)
> 
> I created an org and 2 campaigns. (with dao governance)
> 
> can I have a screenshot where it is supposed to be?

It shows up when you create a proposal and select withdraw as type. Then the campaign dropdown shows up.
(Shows the address because I was on the live version)

image

**Comment by soundyogi** [comment]
thx a lot.
so the campaign has to be finished for this to work right?

**Comment by soundyogi** [comment]
can confirm It works. sorry for being stupid.
merging.

**Review by soundyogi — APPROVED** [review]

**Pull request merged**
