### PR TITLE
Proposal voter list

### PR DESCRIPTION
**Pull request by PAkhidue**
Adds #194

### CODE REVIEW

**Comment by 2075** [comment]
@5-mark @DarkNebula0 any news on this review?

**Review by 5-mark — CHANGES_REQUESTED** [review]
@PAkhidue as it seems more difficult to read the avatar from the polkadot.js wallet please proceed using same visual as members list on organization detail page:
image

**Comment by 2075** [comment]
there is a package for that included in polkadot-js packages

**Comment by 2075** [comment]
lgtm

**Review by 5-mark — APPROVED** [review]

**Pull request merged**
