### PR TITLE
🔍 sy/Refactor - redux ducks to toolkit Immer slices

### PR DESCRIPTION
**Pull request by soundyogi**

### CODE REVIEW

**Comment by DarkNebula0** [comment]
@soundyogi  Would in any case remove the logger middleware only unnecessarily junk in the console.

In case you didn't know, there is a great test tool from redux that will give you all the information you need.

https://github.com/reduxjs/redux-devtools

**Comment by 2075** [comment]
the logger middleware shall be configurable via feature toggles, through dev tools a dev could also manually override, no?

**Comment by soundyogi** [comment]
yes to dev toggle. (or filter the block update action)

yeah I know redux devtools, they are slow and I hate them.

In any case, the logger is only needed when one wants to reason abotu the state flow, so indeed it can be commented out / ppl can use devtools instead.
will fix.

**Comment by DarkNebula0** [comment]
👍 otherwise looks good

**Comment by soundyogi** [comment]
something is still wront with voting - will need to check out again later

**Comment by 2075** [comment]
can you elaborate?
can i help?

**Comment by soundyogi** [comment]
this is basically "just" refactoring the ducks to slices that use immer js 
since we are not super ocnfident with that yet, I want to wait with this one - its also not critical the app works fine.

its just in an A/B testing the voting in this branch doesnt work as it should (yet)

But its really not a pressing matter and we should worry abotu this next week or so

**Comment by 5-mark** [comment]
@soundyogi is this still relevant? if yes, can you try to merge the current status without breaking anything?

**Comment by soundyogi** [comment]
actually, no - not until we go to the newer codebase.
I would like to keep the branch though. closing this.

**Pull request closed without merging**
