### PR TITLE
Update styles and add icons

### PR DESCRIPTION
**Pull request by DarkNebula0**

### CODE REVIEW

**Comment by 2075** [comment]
image

text color white

**Comment by 2075** [comment]
1. what to do with GameDAO and Store buttons?
2. would align logo in sidebar with button on the header and use button height for logo height

**Comment by soundyogi** [comment]
> 1. what to do with GameDAO and Store buttons?
> 2. would align logo in sidebar with button on the header and use button height for logo height

aligned.

no idea about store and gamedao buttons

**Comment by soundyogi** [comment]
https://github.com/gamedaoco/gamedao-beta/issues/66 included

**Comment by soundyogi** [comment]
> image
> 
> text color white

done

**Comment by DarkNebula0** [comment]
Review Done. Already looks more like a finished page ;)

**Pull request merged**
