### PR TITLE
Fix member state 

### PR DESCRIPTION
**Pull request by DarkNebula0**

### CODE REVIEW

**Comment by 2075** [comment]
does not work

**Comment by 2075** [comment]
-click leave
- user should not be member anymore
- ui updates and shows not member
- clicking join 
- user becomes member again
-

**Comment by DarkNebula0** [comment]
> -click leave
> 
> * user should not be member anymore
> * ui updates and shows not member
> * clicking join
> * user becomes member again

@2075  Have you cleared your cache?

https://user-images.githubusercontent.com/91988910/148244561-c32e9d5d-a873-4bbd-93dc-8cf969fa3659.mp4

**Comment by 2075** [comment]
image

**Comment by DarkNebula0** [comment]
Seems to be a chain state problem. What do you get back at gameDaoControl -> memberships(AccountId): Vec<Hash> on the polkadot ui and what is the dao id.

**Pull request merged**
