### PR TITLE
WIP: Proposals

### PR DESCRIPTION
**Pull request by PAkhidue**

### CODE REVIEW

**Comment by 2075** [comment]
fehlt noch was?

**Comment by 2075** [comment]
@PAkhidue any next steps?

**Comment by PAkhidue** [comment]
The only missing stuff is:
- Show vote count (waiting for the things you planned - I can also try to implement that but will need some time)
- And I forgot to check if the wallet already voted

But the rest should work.

**Comment by 2075** [comment]
no worries, maybe just cut the branches smaller, so we can merge more often without fear

**Pull request merged**
