### PR TITLE
🟢 Organizations 

### PR DESCRIPTION
**Pull request by DarkNebula0**

### CODE REVIEW

**Comment by 2075** [comment]
on my end the whole site is black, on mac and linux, bignumber error: 
``` Uncaught TypeError: can't convert BigInt to number
    <anonymous> index.js:41
    u (index):1
    <anonymous> expand.js:1
    u (index):1
    <anonymous> encode.js:1
    u (index):1
    <anonymous> 4.17525727.chunk.js:2
    u (index):1
    823 main.97e1140b.chunk.js:1
    u (index):1
    t (index):1
    r (index):1
    <anonymous> main.97e1140b.chunk.js:1
index.js:41:5

​```

**Comment by 2075** [comment]
Uncaught TypeError: can't convert BigInt to number

**Comment by DarkNebula0** [comment]
Yes Yes. @2075 Local everything works fine. Is once again due to the create-react transpiler

**Comment by 2075** [comment]
maybe that's the reason why i love CRA

**Comment by 2075** [comment]
still no worky :D

**Comment by DarkNebula0** [comment]
image

**Comment by 5-mark** [comment]
same for me, just see a black empty page under https://gamedao-beta-git-feat-organizations-list-75.vercel.app

```
index.js:41 Uncaught TypeError: Cannot convert a BigInt value to a number
    at Math.pow (<anonymous>)
    at Object.<anonymous> (index.js:41)
    at u ((index):1)
    at Object.<anonymous> (expand.js:1)
    at u ((index):1)
    at Object.<anonymous> (encode.js:1)
    at u ((index):1)
    at Object.<anonymous> (4.c919298a.chunk.js:2)
    at u ((index):1)
    at Module.823 (main.8f85d027.chunk.js:1)
```

**Comment by DarkNebula0** [comment]
Pls. Use latest deployed url -> https://gamedao-beta-ix2vgtlu0-75.vercel.app/

**Comment by soundyogi** [comment]
image

deployment URL on top is not updated apparently

**Pull request merged**
