### PR TITLE
Governance fix

### LINKED ISSUE #247: Proposal Title gets empty when typing sth into markdown editor
**Describe the bug**
When entering a proposal title in the create proposal form and tabbing into the markdown editor and start typing the proposal title gets empty. 

**To Reproduce**
1. Go to create proposal page
2. Enter sth into proposal title
3. Enter sth into markdown editor
4. See proposal title gets empty

**Expected behavior**
form values stay in the input fields as long as I dont leave the page

**Additional context**
Maybe sth went wrong with clearing the form fields and not storing the values forever.

### LINKED ISSUE #255: CORS error + Failed : during creation of proposal
**Describe the bug**
Creation of proposal failed. CORS error appears in log

**To Reproduce**
1. Go to your own Organization
2. Click on "Create New Proposal"
3. Select your Organization
4. Filled up Title of Proposal
5. Click "Publish Proposal"

**Expected behavior**
New proposal published

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Firefox
 - Version latest

**Additional context**
I guess Title should be mandatory field. And it must be enforced by FE.

### LINKED ISSUE #256: Proposal Title must be mandatory field
**Describe the bug**
FE allows to create proposal without Title

**To Reproduce**
1. Go to organization you own.
2. Click on Publish new proposal
3. Scroll down to Title
4. See that there no evidence that Title is mandatory field (no *)
5. Click on Publish

**Expected behavior**
No FE warning that title must be entered

**Screenshots**
image

### PR DESCRIPTION
**Pull request by DarkNebula0**
- Closes #256 
- Closes #255 
- Fixes #247

### CODE REVIEW

**Comment by 2075** [comment]
cant verify #247, related to the deployment? @DarkNebula0

**Comment by DarkNebula0** [comment]
> 

Yes seems like vercel has not deployed the last changes

**Review by 2075 — APPROVED** [review]

**Comment by 2075** [comment]
@5-mark please check

**Comment by soundyogi** [comment]
looks good from over here (I need this to finish my PR aswell)

**Review by soundyogi — APPROVED** [review]

**Comment by 5-mark** [comment]
also tested the PR now. Works 👍🏼

**Pull request merged**
