### PR TITLE
feat: new wallet layout according(ish) to figma/

### PR DESCRIPTION
**Pull request by michelalbers**

### CODE REVIEW

**Comment by soundyogi** [comment]
conflict

**Comment by DarkNebula0** [comment]
Ich mach gerade noch ein paar Änderungen.

**Comment by 5-mark** [comment]
@michelalbers, somehow it does not look like in figma:
image
heart is not pixeled, background is not white, logout is not separated. Currency amounts should be right-aligned  and the currencies left-aligned.

**Comment by 2075** [comment]
questions:
- how do you see the digits after the decimal separator? our currencies have on average 18.
- why disconnect button separate? (plus could it be an unplug icon?)
@mikeplanzer

**Comment by 5-mark** [comment]
@mikeplanzer please prepare some design considering the input from @2075. But for this ticket @michelalbers please try to make it look a little more (or as much as possible) like figma. 
Please use max 3 decimals for each currency, rounding up the 3rd decimal.

**Pull request merged**
