### PR TITLE
WIP: feat: introduce list and tile view with switch

### PR DESCRIPTION
**Pull request by michelalbers**

### CODE REVIEW

**Comment by 2075** [comment]
nice! @michelalbers 

1. is this wip or complete?
2. wondering where the images are 
3. can the tiles fill the rows? imagine a huge netflix wall of items:
image
4. does it paginate or load moar on scroll?

**Comment by 2075** [comment]
#50

**Comment by 2075** [comment]
@michelalbers would love to use this in tangram, waiting for exactly this since a while, can we split it from your app views? can also merge und you keep working in this branch.

**Comment by michelalbers** [comment]
@2075 Code should now be modular enough to use the new components wherever you need ;)

**Pull request merged**
