### PR TITLE
 feat(validation): add validation proposals

### PR DESCRIPTION
**Pull request by soundyogi**
## Proposed changes

Adds Formik Form Validation to Proposal Creation Form

## Checklist

- [ ] Proposal Creation Works

### CODE REVIEW

**Comment by 5-mark** [comment]
@soundyogi review OK ✅

**Comment by 2075** [comment]
renders black screen and errors in console

**Review by 5-mark — CHANGES_REQUESTED** [review]
cannot submit the proposal form and no error is logged in the browser console.
Please fix 😄

**Review by 5-mark — APPROVED** [review]
proposals can be created again :-)

**Pull request merged**
