### PR TITLE
fix: orga account zero addr validator

### LINKED ISSUE #272: Cannot create organization as address is not recognised as valid
**Describe the bug**
When trying to create an organization I get an error message regarding my address format even though it is a correct Zero address.

**To Reproduce**
1. Go to Organizations and click  +New DAO
2. See Controller and Treasury Account contains no Zero address
3. add 2 different zero addresses
4. See error saying invalid account
5.

**Expected behavior**
Zero account wallets should be valid.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by soundyogi**
# Description

The Form Address Validator is broken.

Closes #272 

## Type of change

- [ ] toZeroAddress() in validator to check address

# Test:

- [ ] Paste Addresses for Treasury and Controller

### CODE REVIEW

**Comment by 2075** [comment]
frontend apes when sending a create dao tx

**Comment by soundyogi** [comment]
getting nonce too low messages now too....

**Comment by soundyogi** [comment]
But this is unrelated to the PR I think?

**Comment by 2075** [comment]
hm, cant test unless i roll back the previous merge... will merge for now but without fixing the tx the frontend cannot be used.

**Comment by 2075** [comment]
btw, do you validate if the address is a substrate compatible address or if it is zero network specific?

**Comment by soundyogi** [comment]
I use the toZeroAddress() Andre created - And I believe it checks for our network prefix.

**Pull request merged**
